version: "3.9"

services:

  admin-app:
    container_name: yn-admin
    image: yn-admin
    build: ./admin
    ports:
      - "3001:3000"

  app:
    container_name: your-norm
    image: your-norm
    build: ./client
    ports:
      - "3000:3000"

  server:
    container_name: backend
    image: backend
    build: ./server
    ports:
     - "8000:8000"