version: "3.9"

services:

  app:
    environment:
      - NODE_ENV=production
    command: npm start

  admin-app:
    environment:
      - NODE_ENV=production
    command: npm start

  server:
    build:
      context: ./server
      args:
        - NODE_ENV=production
    environment:
      - MONGO_USERNAME=yourname
      - MONGO_PASSWORD=yourpassword
      - MONGO_URI=youruri
      - NODE_ENV=production
    command: node index.js